version: "3"


services:
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Con esta sintaxis se toma el dato en .env
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumnes: # Configuacion para no perder la información si se destruye o monta el contenedor
      - ./postgres:/var/lib/postgresql/data # Ubicación donde estará grabándose la información en el contenedor